config/routes.rb
Rails.application.routes.draw do

  resources :agendas
  #map.connect '/reservacions/solicitud', :controller => 'reservacions', :action => 'solicitud'
  
  resources :reservacions
  resources :welcome
  resources :calendario
  resources :reservacion
  resources :espacios
  resources :videoconferencia
  devise_for :users
  resources :users
  resources :reservacions, :member => {:solicitud => :get}
  
  
  root 'welcome#solicitud'

  get 'welcome/solicitud'
  post 'welcome/solicitud'

  get 'users/new'
  get 'users/edit'

  get 'welcome/administracion'
  post 'welcome/administracion'
   
  get 'calendario/espacios'
  post 'calendario/espacios'

  post 'calendario/salaVideoconferencia'

  post 'calendario/actividadesInvestigacion'
  post 'calendario/calendarioGeneral'

  get '/calendario/pdfs'
  #post '/calendario/pdfs'

  
  get 'espacios/auditorio4P'
  post 'espacios/auditorio4P'

  get 'espacios/sala15P'
  post 'espacios/sala15P'

  get   'espacios/sala25P'
  post 'espacios/sala25P'
 
  get   'espacios/auditorioRG'
  post 'espacios/auditorioRG'

  get 'espacios/sala6P'
  post 'espacios/sala6P'
 
  get 'espacios/salaPosg'
  post'espacios/salaPosg'

  get 'espacios/espacioAdic'
  post 'espacios/espacioAdic'


  get 'espacios/salaVideoconferencias'
  post 'espacios/salaVideoconferencias'

  get 'reservacions/new'
  get 'reservacions/show'
  get 'reservacions/formSala6', to: "reservacions#new"


  post '/reservacions/actividadesInvestigacion', to: 'reservacions#show'
  post '/reservacions/id', to: 'reservacions#show'
  post '/videoconferencia/id',  to: 'videoconferencia#show'

  get 'agendas/new'
  get 'agendas/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/welcome.rb
class Welcome < ApplicationRecord

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user! 
 

  def show
  	render 'welcome/solicitud'
  end

  def login
  	
  	solicituds[:usuario_id] = nil
    solicituds[:admin] = nil
    @usuario = Usuarios.new
  end

end

app/views/welcome/_administracion.html.erb
<%= render 'welcome/encabezado', welcome: @welcome %>
<% if can? :manage, Welcome %>
    <div class= "contenedor">
        <div class="panel-group">     
            <div class="panel panel-default">
                <div class="panel-heading">Programación de actividades </div>
                <div class="panel-body">
                    <center>
                        <div class="btn-group" role="group" aria-label="...">
                            <center>
                                <% if can? :manage, Espacio %>
                                    <a class="btn btn-primary btn-large">
                                        <%= button_to 'Espacios', espacios_path, :method => :get  %> </a>
                                <% end %>
                                <% if can? :manage, Reservacion %>
                                    <a class="btn btn-primary btn-large">
                                        <%= button_to 'Reservaciones', reservacions_path, :method => :get  %> </a>
                                <% end %>
                                <% if can? :manage, Videoconferencium %>
                                    <a class="btn btn-primary btn-large">
                                        <%= button_to 'Sala de Videoconferencias', videoconferencia_path, :method => :get  %> </a>
                                <% end %>
                                <% if can? :manage, Calendario %>
                                    <a class="btn btn-primary btn-large">
                                        <%= button_to 'Calendarios', agendas_new_path, :method => :get  %> </a>
                                <% end %>
                                <% if can? :manage, User%>
                                    <a class="btn btn-primary btn-large">
                                        <%= button_to 'Usuarios', users_path, :method => :get  %> </a>
                                <% end %>
                            </center>
                        </div>
                    </center>
                </div>
            </div>      
        </div>
    </div>
</div>
<% end %>

app/views/welcome/_encabezado.html.erb
<!DOCTYPE html>
<html>
<link href="https://goo.gl/34igzK" rel="shortcut icon">
  <title>Sistema de Gestión de Espacios </title>
  <!-- Latest compiled and minified CSS -->
  <head>
  <link rel="stylesheet" href="https://bootswatch.com/3/flatly/bootstrap.min.css">
    <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://bootswatch.com/3/flatly/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application'%>
    <%= javascript_include_tag "application"%>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="contenedor">
      <div class="encabezado"><a href="http://www.unam.mx" target="_blank"><img src="https://www.ceiich.unam.mx/0/img/encabezadoLogo01.png" alt="Visita la web de la UNAM" border="0" width="250" height="119" /></a><a href="http://www.ceiich.unam.mx"><img src="https://www.ceiich.unam.mx/0/img/encabezadoLogo02.png" title="Regreso home del CEIICH"  title="Visita la web de la UNAM" border="0" width="1030" height="119"/></a></div> 

      <div class="container">
        <div class="jumbotron">
          <center>
            <h2>SISTEMA DE GESTIÓN DE ESPACIOS</h2>
          </center>
        </div>
        <div id="user_nav">
          <div align="right">
          <p class="notice"><%= notice %></p><p class="alert"><%= alert %></p> </div>
          <% if user_signed_in? %>
            <div align="left">
              <% if can? :show, Reservacion %>
                <a class="btn btn-default">
                <span class="glyphicon glyphicon-home"></span>
                <%= button_to 'Inicio', root_path, :method => :get %>
                </a>
              <% end %>
            </div>
            <div align="right">
              Conectado como <%= current_user.email %>. 
              <%= button_to  "Cerrar sesión", destroy_user_session_path, :method => :delete %>
            </div>
          <% end %>
         
        </div>
        <% if can? :manage, Welcome %>                
          <div class= "container">
            <div class="panel-group">     
              <div class="panel panel-default">
                <div class="panel-heading"></div>
                  <div class="panel-body">
                    <center>
                      <div class="btn-group" role="group" aria-label="...">
                        <center>
                          <a class="btn btn-primary btn-large"><%= button_to "Administración", welcome_administracion_path %></a>
                        </center>
                      </div>
                    </center>
                  </div>
              </div>      
            </div>
          </div>
          </br></br>
        <% end %>
      </div>
    </div>
      <%= yield %>

  </body>
</html>

app/views/welcome/_piePagina.html.erb
<!DOCTYPE html>
<html>
<link href="https://goo.gl/34igzK" rel="shortcut icon">
  <title>Sistema de Gestión de Espacios </title>
  <!-- Latest compiled and minified CSS -->
  <head>
  <link rel="stylesheet" href="https://bootswatch.com/3/flatly/bootstrap.min.css">
    <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://bootswatch.com/3/flatly/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application'%>
    <%= javascript_include_tag "application"%>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
      <%= yield %>
      
    <div class= "contenedor">
      <footer>
        <strong> 
          <div class="pie-banners">
            <%= image_tag "vinculosExternos.jpg", usemap:"#imagen01"%>
          </div>
          <div class="pie-derechos">
            <div align="center"> Hecho en México, todos los derechos reservados 2018. Esta página puede ser reproducida con fines no lucrativos, siempre y cuando no se mutile, <br/>
             se cite la fuente completa y su dirección electrónica. De otra forma requiere permiso previo por escrito de la institución.
            </div>
            <div class="administrado">Sitio web creado y administrado por el Departamento de Cómputo del Centro de Investigaciones Interdisciplinarias en Ciencias y Humanidades (CEIICH).<br/>
             Contacto: <a href="mailto:sge.reservaciones@ceiich.unam.mx">sge.reservaciones@ceiich.unam.mx</a>
            </div>
          </div> 
        </strong>
      </footer>
  </div>
  </body>
</html>

app/views/welcome/_piePagina1.html.erb
<!DOCTYPE html>
<html>
<link href="https://goo.gl/34igzK" rel="shortcut icon">
  <title>Sistema de Gestión de Espacios </title>
  <!-- Latest compiled and minified CSS -->
  <head>
  <link rel="stylesheet" href="https://bootswatch.com/3/flatly/bootstrap.min.css">
    <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://bootswatch.com/3/flatly/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application'%>
    <%= javascript_include_tag "application"%>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
      <%= yield %>
      
    <div class= "contenedor">
      <footer>
        <strong> 
          <div class="pie-banners">
            <%= image_tag "vinculosExternos.jpg", usemap:"#imagen01"%>
          </div>
          <div class="pie-derechos1">
            <div align="center"> Hecho en México, todos los derechos reservados 2018. Esta página puede ser reproducida con fines no lucrativos, siempre y cuando no se mutile, <br/>
             se cite la fuente completa y su dirección electrónica. De otra forma requiere permiso previo por escrito de la institución.
            </div>
            <div class="administrado1">Sitio web creado y administrado por el Departamento de Cómputo del Centro de Investigaciones Interdisciplinarias en Ciencias y Humanidades (CEIICH).<br/>
             Contacto: <a1 href="mailto:sge.reservaciones@ceiich.unam.mx">sge.reservaciones@ceiich.unam.mx</a>
            </div>
          </div> 
        </strong>
      </footer>
    </br>
  </div>
  </body>
</html>

app/views/welcome/administracion.html.erb
<%= render 'welcome/encabezado', welcome: @welcome %>

<% if can? :manage, Welcome %>
    <div class= "contenedor">
        <div class="panel-group">     
            <div class="panel panel-default">
                <div class="panel-heading">Programación de actividades </div>
                <div class="panel-body">
                    <center>
                        <div class="btn-group" role="group" aria-label="...">
                            <center>
                                <% if can? :manage, Espacio %>
                                    <a class="btn btn-primary btn-large">
                                        <%= button_to 'Espacios', espacios_path, :method => :get  %> </a>
                                <% end %>
                                <% if can? :manage, Reservacion %>
                                    <a class="btn btn-primary btn-large">
                                        <%= button_to 'Reservaciones', reservacions_path, :method => :get  %> </a>
                                <% end %>
                                <% if can? :manage, Videoconferencium %>
                                    <a class="btn btn-primary btn-large">
                                        <%= button_to 'Sala de Videoconferencias', videoconferencia_path, :method => :get  %> </a>
                                <% end %>
                                <% if can? :manage, Calendario %>
                                    <a class="btn btn-primary btn-large">
                                        <%= button_to 'Calendarios', agendas_new_path, :method => :get  %> </a>
                                <% end %>
                                <% if can? :manage, User%>
                                    <a class="btn btn-primary btn-large">
                                        <%= button_to 'Usuarios', users_path, :method => :get  %> </a>
                                <% end %>
                            </center>
                        </div>
                    </center>
                </div>
            </div>      
        </div>
    </div>
</div>
<% end %>
<%= render 'welcome/piePagina', welcome: @welcome %>

app/views/welcome/solicitud.html.erb
<%= render 'encabezado', welcome: @welcome %>
<%if can? :show, Videoconferencium %>
 <style type="button">
  input {color: black;}
 </style>
  <div class="container">
   <h4 align="center">RESERVACIÓN SALA DE VIDEOCONFERENCIAS</h4></br></br></br>
    <div class="row">
       <div class="col-md-6">
          <div class="jumbotron5">
            <center>
              <a class="btn btn-primary btn-large">
                <%= button_to 'Ver disponibilidad', calendario_salaVideoconferencia_path, :method => :post %>
              </a>
            </center>
          </div>
       </div>

       <div class="col-md-6" >
        <div class="jumbotron6">
          <center>
            <a class="btn btn-primary btn-large">
              <%= button_to 'Solicitar espacio', new_videoconferencium_path, :method => :get %>
            </a>
          </center>
        </div>
      </div>
    </div>
  </div> 
<% end %>
</br></br></br></br>
<% if can? :manage, Reservacion %>
 <div class="container">
  <h4 align="center">RESERVACIÓN DE SALAS</h4></br></br></br>
    <div class="row">
      <div class="col-md-6" >
        <div class="jumbotron2">
 	        <center>
            <a class="btn btn-primary btn-large">
              <%= button_to 'Ver disponibilidad', calendario_calendarioGeneral_path, :method => :post %>
            </a>
          </center>
        </div>            
      </div>
   
      <div class="col-md-6" >
 	      <div class="jumbotron3">
 		      <center>
 	          <a class="btn btn-primary btn-large">
              <%= button_to 'Solicitar espacio', new_reservacion_path, :method => :get %>
            </a>
          </center>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% if cannot? :delete, Reservacion %>
  <div class="container">
    <h4 align="center">RESERVACIÓN DE SALAS</h4></br></br></br>
      <div class="jumbotron2">
            <center>
              <a class="btn btn-primary btn-large">
                <button type="button" data-toggle="modal" id="disponibilidad">Ver disponibilidad de espacios</button>
              </a>
            </center>
                    <div id="Asistentes" class="modal fade" role="dialog">
                      <div class="modal-dialog">
                        <center>

                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title"></h4>
                        </div>
                           <div class="modal-body">
                           </br>
                             <h5> Si requiere reservar algún auditorio, por favor comuníquese con el</br></br> Departamento de Difusión</h5>
                           </div>

                          <div class="modal-footer">
                            <center>
                              <a class="btn btn-primary btn-large">
                                <%= button_to 'Ver disponibilidad', calendario_calendarioGeneral_path, :method => :post %>
                              </a>
                            </center>
                          </div>            
                      </div>
                        </center>
                      </div>
                    </div>      

                    <script>
                     $(document).ready(function(){
                     $("#disponibilidad").click(function(){
                     $("#Asistentes").modal();
                      });
                    });
                    </script>
      </div>
  </div>
<% end %>
 <%= render 'welcome/piePagina', welcome: @welcome %>