config/routes.rb
Rails.application.routes.draw do

  resources :agendas
  #map.connect '/reservacions/solicitud', :controller => 'reservacions', :action => 'solicitud'
  
  resources :reservacions
  resources :welcome
  resources :calendario
  resources :reservacion
  resources :espacios
  resources :videoconferencia
  devise_for :users
  resources :users
  resources :reservacions, :member => {:solicitud => :get}
  
  
  root 'welcome#solicitud'

  get 'welcome/solicitud'
  post 'welcome/solicitud'

  get 'users/new'
  get 'users/edit'

  get 'welcome/administracion'
  post 'welcome/administracion'
   
  get 'calendario/espacios'
  post 'calendario/espacios'

  post 'calendario/salaVideoconferencia'

  post 'calendario/actividadesInvestigacion'
  post 'calendario/calendarioGeneral'

  get '/calendario/pdfs'
  #post '/calendario/pdfs'

  
  get 'espacios/auditorio4P'
  post 'espacios/auditorio4P'

  get 'espacios/sala15P'
  post 'espacios/sala15P'

  get   'espacios/sala25P'
  post 'espacios/sala25P'
 
  get   'espacios/auditorioRG'
  post 'espacios/auditorioRG'

  get 'espacios/sala6P'
  post 'espacios/sala6P'
 
  get 'espacios/salaPosg'
  post'espacios/salaPosg'

  get 'espacios/espacioAdic'
  post 'espacios/espacioAdic'


  get 'espacios/salaVideoconferencias'
  post 'espacios/salaVideoconferencias'

  get 'reservacions/new'
  get 'reservacions/show'
  get 'reservacions/formSala6', to: "reservacions#new"


  post '/reservacions/actividadesInvestigacion', to: 'reservacions#show'
  post '/reservacions/id', to: 'reservacions#show'
  post '/videoconferencia/id',  to: 'videoconferencia#show'

  get 'agendas/new'
  get 'agendas/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/videoconferencia_controller.rb
class VideoconferenciaController < ApplicationController
  protect_from_forgery
  before_action :set_videoconferencium, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :handle_record_not_found
  respond_to :json
  # GET /videoconferencia
  # GET /videoconferencia.json
  def handle_record_not_found
    redirect_to calendario_salaVideoconferencia_path, method: :post, :notice => "Verifique su folio de reservación."
  end

  def index
    @videoconferencia = Videoconferencium.all
  end

  # GET /videoconferencia/1
  # GET /videoconferencia/1.json
  def show
      @videoconferencium  = Videoconferencium.find_by_id(params[:id])
  end

  # GET /videoconferencia/new
  def new
    @videoconferencium = Videoconferencium.new
  end

  # GET /videoconferencia/1/edit
  def edit
    @videoconferencium = Videoconferencium.find_by_id(params[:id])
  end

  # POST /videoconferencia
  # POST /videoconferencia.json
  def create
    @videoconferencium = Videoconferencium.new(videoconferencium_params)
    @videoconferencium.save

    respond_to do |format|
      if @videoconferencium.save
        format.html { redirect_to @videoconferencium, notice: 'La reservación fue creada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @videoconferencium }
      else
        format.html { render :new }
        format.json { render json: @videoconferencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videoconferencia/1
  # PATCH/PUT /videoconferencia/1.json
  def update
    respond_to do |format|
      if @videoconferencium.update(videoconferencium_params)
        format.html { redirect_to @videoconferencium, notice: 'La información ha sido actualizada satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @videoconferencium }
      else
        format.html { render :edit }
        format.json { render json: @videoconferencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videoconferencia/1
  # DELETE /videoconferencia/1.json
  def destroy
    @videoconferencium.destroy
    respond_to do |format|
      format.html { redirect_to videoconferencia_url, notice: 'La reservación fue eliminada satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_videoconferencium
      @videoconferencium = Videoconferencium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def videoconferencium_params
      params.require(:videoconferencium).permit(:nSolicitante, :tituloActividad, :fechaActividad, :coordinador, :tipoEnlace, :horainicio, :horafin, :coordinadorEnlace, :responsableTecnico, :numeroIP, :usuarioTipoEnlace, :telefono, :correoElectronico, :recursos, :horainicioEnlace, :horafinEnlace, :usuario, :fechaSolicitud, :aprobacion)
    end
end

app/helpers/videoconferencia_helper.rb
module VideoconferenciaHelper
end

app/views/videoconferencia/_form.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  
<%= form_with(model: videoconferencium, local: true) do |form| %>
  <% if videoconferencium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(videoconferencium.errors.count, "error") %> prohibited this videoconferencium from being saved:</h2>
      <ul>
      <% videoconferencium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class = "contenedor">
  <div class="container">
    <div class="jumbotron4">
      <center>
  
        <div class="field">
          <%= form.label :nombre_del_solicitante %>
          <%= form.text_field :nSolicitante, id: :videoconferencia_nSolicitante, required:"" %>
        </div>

        <div class="field">
          <%= form.label :título_de_la_actividad %>
          <%= form.text_field :tituloActividad, id: :videoconferencia_tituloActividad, required:"" %>
        </div>

        <div class="field">
          <%= form.label :coordinador_del_encuentro%>
          <%= form.text_field :coordinador, id: :videoconferencia_coordinador, required:"" %>
        </div>

        <div class="field">
          <%= form.label :fecha_de_la_actividad %>
          <%= form.date_field :fechaActividad, id: :videoconferencia_fechaActividad, :value => Time.zone.today + 5.day, min:Time.zone.today %>
        </div>

        <div class="field">
          <%= form.label :tipo_de_enlace%>
          <%= form.text_field :tipoEnlace, id: :videoconferencia_tipoEnlace, placeholder: 'Skype, Hangouts, Messenger, Blackboard, otro', required:""%>
        </div>

        <div class="field">
          <%= form.label :hora_de_inicio %>
          <%= form.time_field :horainicio, id: :videoconferencia_horainicio, :value => "08:00", min: "07:00", max: "20:00" %>
        </div>

        <div class="field">
          <%= form.label :hora_de_fin %>
          <%= form.time_field :horafin, id: :videoconferencia_horafin, :value => "10:00", min: "07:00", max: "20:00"%></br>
          <h7>*Tiempo de la Ciudad de México </h7>
        </div>

        
        <% if can? :manage, Videoconferencium %>
        <div class="field">
          <%= form.label :aprobacion %>
          <%= form.check_box :aprobacion, id: :videoconferencia_aprobacion %>
        </div>
        <% end %>


        <div class="field">
          <%= form.label :fecha_de_solicitud %>
          <%= Time.now.strftime("%d-%m-%Y") %>
          <%= form.hidden_field :fechaSolicitud, id: :videoconferencia_fechaSolicitud, :value => Time.now.strftime("%d-%m-%Y") %>
        </div>

        <div class="field">
          <%= form.hidden_field :usuario, id: :videoconferencia_usuario, :value => current_user.email %>
        </div>
         

  <button type="button" class="btn btn-primary btn-sm" id="myBtn">Crear reservación</button>

  <!-- Modal -->
  <div class="modal fade" id="Servicios" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">DATOS DEL ENLACE</h4>
        </div>
        <div class="modal-body">
            
            <div class="field"> <%= form.label :coordinador_del_encuentro %><%= form.text_field :coordinadorEnlace, id: :videoconferencia_coordinadorEnlace, placeholder: 'En la sede enlace' %></div> 
            <div class="field"><%= form.label :responsable_técnico %><%= form.text_field :responsableTecnico, id: :videoconferencia_responsableTecnico %></div> 
            <div class="field"><%= form.label :dirección_ip %><%= form.text_field :numeroIP, id: :videoconferencia_IP, min: "1", placeholder: 'En caso de videoconferencia'%></div> 
            <div class="field"><%= form.label :usuario %><%= form.text_field :usuarioTipoEnlace, id: :videoconferencia_usuarioTipoEnlace, placeholder: 'Skype, Hangouts, Messenger, Blackboard, otro'%></div>
            <div class="field"><%= form.label :teléfono %><%= form.text_field :telefono, id: :videoconferencia_telefono %></div> 
            <div class="field"><%= form.label :correo_electrónico%><%= form.text_field :correoElectronico, id: :videoconferencia_correoElectronico %></div> 
            <div class="field"><%= form.label :recursos%><%= form.text_area :recursos, rows: "5", id: :videoconferencia_recursos, placeholder: 'Especificar si durante el enlace se utilizará alguna herramienta de apoyo (Presentación PowerPoint, archivo de audio o video).' %></div> 
            <div class="field"><%= form.label :hora_de_inicio %> <%= form.time_field :horainicioEnlace, id: :videoconferencia_horainicioEnlace, :value => "08:00" %> </div>
            <div class="field"><%= form.label :hora_de_fin %><%= form.time_field :horafinEnlace, id: :videoconferencia_horafinEnlace, :value => "10:00" %></br> <h7>*Horario de la sede enlace </h7> </div>
            
            <div class="actions">
            <a class="btn btn-primary btn-sm">
            <%= form.submit t('.submit', :default => "Crear reservación") %> </a> 
            </div>
        </div>   
      </div>   
    </div>
  </div>


<script>
$(document).ready(function(){
    $("#myBtn").click(function(){
        $("#Servicios").modal();
    });
});
</script>
        <% end %>
      </center>
    </div>
    <div align ="right">
      <a class="btn btn-primary btn-large">
            <%= button_to 'Regresar', calendario_salaVideoconferencia_path, :method => :post %>
      </a>
    </div>
  </div>
</div>

app/views/videoconferencia/_formEdit.html.erb
<%= form_with(model: videoconferencium, local: true) do |form| %>
  <% if videoconferencium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(videoconferencium.errors.count, "error") %> prohibited this videoconferencium from being saved:</h2>

      <ul>
      <% videoconferencium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class = "contenedor">
  <div class="container">
    <div class="jumbotron4">
      <center>
  
        <div class="field">
          <%= form.label :nombre_del_solicitante %>
          <%= form.text_field :nSolicitante, id: :videoconferencia_nSolicitante %>
        </div>

        <div class="field">
          <%= form.label :título_de_la_actividad %>
          <%= form.text_field :tituloActividad, id: :videoconferencia_tituloActividad %>
        </div>

        <div class="field">
          <%= form.label :coordinador_del_encuentro%>
          <%= form.text_field :coordinador, id: :videoconferencia_coordinador %>
        </div>

        <div class="field">
          <%= form.label :fecha_de_la_actividad %>
          <%= form.date_field :fechaActividad, id: :videoconferencia_fechaActividad%>
        </div>

        <div class="field">
          <%= form.label :tipo_de_enlace%>
          <%= form.text_field :tipoEnlace, id: :videoconferencia_tipoEnlace%>
        </div>

        <div class="field">
          <%= form.label :hora_de_inicio %>
          <%= form.time_field :horainicio, id: :videoconferencia_horainicio %>
        </div>

        <div class="field">
          <%= form.label :hora_de_fin %>
          <%= form.time_field :horafin, id: :videoconferencia_horafin%></br>
          <h7>*Tiempo de la Ciudad de México </h7>
        </div>

        
        <% if can? :manage, Videoconferencium %>
        <div class="field">
          <%= form.label :aprobación %>
          <%= form.check_box :aprobacion, id: :videoconferencia_aprobacion %>
        </div>
        <% end %>


        <div class="field">
          <%= form.label :fecha_de_solicitud %>
          <%= form.text_field :fechaSolicitud, id: :videoconferencia_fechaSolicitud, :readonly => true %>
        </div>

        <div class="field">
          <%= form.hidden_field :usuario, id: :videoconferencia_usuario, :readonly => true %>
        </div>
         

  <button type="button" class="btn btn-primary btn-sm" id="myBtn">Crear reservación</button>

  <!-- Modal -->
  <div class="modal fade" id="Servicios" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">DATOS DEL ENLACE</h4>
        </div>
        <div class="modal-body">
            
            <div class="field"><%= form.label :coordinador_del_encuentro %><%= form.text_field :coordinadorEnlace, id: :videoconferencia_coordinadorEnlace%></div> 
            <div class="field"><%= form.label :responsable_técnico %><%= form.text_field :responsableTecnico, id: :videoconferencia_responsableTecnico %></div> 
            <div class="field"><%= form.label :dirección_ip %><%= form.text_field :numeroIP, id: :videoconferencia_IP, min: "1" %></div> 
            <div class="field"><%= form.label :usuario %><%= form.text_field :usuarioTipoEnlace, id: :videoconferencia_usuarioTipoEnlace%></div>
            <div class="field"><%= form.label :teléfono %><%= form.text_field :telefono, id: :videoconferencia_telefono%></div> 
            <div class="field"><%= form.label :correo_electrónico%><%= form.text_field :correoElectronico, id: :videoconferencia_correoElectronico %></div> 
            <div class="field"><%= form.label :recursos%><%= form.text_area :recursos, rows: "5", id: :videoconferencia_recursos%></div> 
            <div class="field"><%= form.label :hora_de_inicio %> <%= form.time_field :horainicioEnlace, id: :videoconferencia_horainicioEnlace %> </div>
            <div class="field"><%= form.label :hora_de_fin %><%= form.time_field :horafinEnlace, id: :videoconferencia_horafinEnlace %></br> <h7>*Horario de la sede enlace </h7> </div>
            
            <div class="actions">
            <a class="btn btn-primary btn-sm">
            <%= form.submit t('.submit', :default => "Crear reservación") %> </a> 
            </div>
        </div>   
      </div>   
    </div>
  </div>


<script>
$(document).ready(function(){
    $("#myBtn").click(function(){
        $("#Servicios").modal();
    });
});
</script>
        <% end %>
      </center>
    </div>
    <div align ="right">
      <a class="btn btn-primary btn-large">
            <%= button_to 'Regresar', calendario_salaVideoconferencia_path, :method => :post %>
      </a>
    </div>
  </div>
</div>

app/views/videoconferencia/edit.html.erb
<%= render 'welcome/encabezado', welcome: @welcome %>
<center><h2>EDICIÓN DE LA RESERVACIÓN</h2></center>
<%= render 'formEdit', videoconferencium: @videoconferencium %>
<%= render 'welcome/piePagina', welcome: @welcome %>

app/views/videoconferencia/index.html.erb
<%= render 'welcome/encabezado', welcome: @welcome %>
<p id="notice"><%= notice %></p>
<% if can? :manage, Reservacion %>
<div class= "contenedor">
    <div class="panel-group">     
        <div class="panel panel-default">
          <div class="panel-heading">Programación de actividades </div>
            <div class="panel-body">
             <center>
              <div class="btn-group" role="group" aria-label="...">
                <center>
                 <% if can? :manage, Espacio %>
                 <a class="btn btn-primary btn-large">
                 <%= button_to 'Espacios', espacios_path, :method => :get  %> </a>
                 <% end %>
                 <% if can? :manage, Reservacion %>
                 <a class="btn btn-primary btn-large">
                 <%= button_to 'Reservaciones', reservacions_path, :method => :get  %> </a>
                 <% end %>
                  <% if can? :manage, Videoconferencium %>
                 <a class="btn btn-primary btn-large">
                 <%= button_to 'Sala de Videoconferencias', videoconferencia_path, :method => :get  %> </a>
                 <% end %>
                 <% if can? :manage, Calendario %>
                 <a class="btn btn-primary btn-large">
                 <%= button_to 'Calendarios', calendario_espacios_path, :method => :post  %> </a>
                 <% end %>
                 <% if can? :manage, User%>
                 <a class="btn btn-primary btn-large">
                 <%= button_to 'Usuarios', users_path, :method => :get  %> </a>
                 <% end %>
               </center>
              </div>
             </center>
            </div>
        </div>      
    </div>
</div>
<% end %>

<% if can? :manage, Videoconferencium %>

<div class= "contenedor">
 <h1 align="center">Reservaciones</h1><h4 align="center">SALA DE VIDEOCONFERENCIAS</h4>
  <div align="right"> <h4><%= link_to 'Nueva reservación', new_videoconferencium_path, :method => :get %></h4></div>

    <% @videoconferencia = @videoconferencia.reverse%>
    <% @videoconferencia.each do |videoconferencium| %>
 
    <div class="panel panel-primary">
      <div class="panel-body">
        <div class="col-md-6" >
         <ul class="list-group">
          <li class="list-group-item list-group-item-info"> <b>Folio de reservación: <%= videoconferencium.id %></b></li>

          <% if videoconferencium.aprobacion == true %>
          <li class="list-group-item list-group-item-success">  Aprobación: Aprobada </li>
          <% else %>
          <li class="list-group-item list-group-item-danger"> Aprobación: Pendiente </li>
          <% end %> 

          <center><h4>DATOS DEL SOLICITANTE</h4></center>
          <li class="list-group-item"> <b>Nombre del solicitante: <%= videoconferencium.nSolicitante %></b></li>
          <li class="list-group-item"> Título de la actividad: <%= videoconferencium.tituloActividad %> </li>
          <li class="list-group-item"> <b>Coordinador del encuentro: <%= videoconferencium.coordinador %>  </b></li>
          <li class="list-group-item"> Fecha de la actividad: <%= videoconferencium.fechaActividad %></li>
          <li class="list-group-item"> <b>Tipo de enlace: <%= videoconferencium.tipoEnlace %> </b></li>
          <li class="list-group-item"> Hora de inicio: <%= videoconferencium.horainicio %></li>
          <li class="list-group-item"> <b>Hora de fin: <%= videoconferencium.horafin %></b></li>
          <li class="list-group-item"> Fecha de solicitud: <%= videoconferencium.fechaSolicitud %></li>
          <li class="list-group-item"> <b>Usuario: <%= videoconferencium.usuario %></b> </li>
         
         </ul>
        </div>
        <div class="col-md-6" >
           <ul class="list-group">
           </br> </br>
            <center><h4>DATOS DEL ENLACE</h4></center>
            <li class="list-group-item"> <b>Coordinador del encuentro: <%= videoconferencium.coordinadorEnlace %></b> </li>
            <li class="list-group-item"> Responsable técnico: <%= videoconferencium.responsableTecnico %> </li>
            <li class="list-group-item"> <b>Dirección IP: <%= videoconferencium.numeroIP %></b> </li>
            <li class="list-group-item"> Usuario del tipo de enlace: <%= videoconferencium.usuarioTipoEnlace %> </li>
            <li class="list-group-item"> <b>Teléfono: <%= videoconferencium.telefono %></b> </li>
            <li class="list-group-item"> Correo electrónico: <%= videoconferencium.correoElectronico %> </li>
            <li class="list-group-item"> <b>Recursos: <%= videoconferencium.recursos %></b> </li>
            <li class="list-group-item"> Hora de inicio: <%= videoconferencium.horainicioEnlace %></li>
            <li class="list-group-item"> <b>Hora de fin: <%= videoconferencium.horafinEnlace %></b> </li>
          </ul>
         </div> 
          <table class="table table-striped table-hover">
          <tbody>
             <tr>
              <td><%= link_to 'Mostrar', videoconferencium, :method => :get %></td>
              <td><%= link_to 'Editar', edit_videoconferencium_path(videoconferencium), :method => :get %></td>
              <td><%= link_to 'Eliminar', videoconferencium, method: :delete, data: { confirm: '¿Desea continuar?' } %></td>
              <!-- <td><%= link_to 'Descargar solicitud', reservacions_path(format: 'pdf')%></td> -->
             </tr>
          </tbody>
          </table>    
      </div>
    </div>
<% end %>
</div>

<% end %>
<% if cannot? :manage, Videoconferencium  %>
<div class= "contenedor">
    <div class="panel panel-default">
        <div class="panel-heading">Programación de actividades </div>
            <div class="panel-body"> 
                <center>
                  <div> No tienes acceso a esta página.</div>
                 <a class="btn btn-primary btn-large">
                 <%= button_to 'Regresar', calendario_actividadesInvestigacion_path, :method => :get %>
                 </a>
                 </center>
          
            </div>
        </div>      
</div>
<% end %>
<%= render 'welcome/piePagina', welcome: @welcome %>

app/views/videoconferencia/new.html.erb
<%= render 'welcome/encabezado', welcome: @welcome %>
<% if can? :show, Videoconferencium %>
<center><h2>NUEVA SOLICITUD</h2></center>

<%= render 'form', videoconferencium: @videoconferencium %>

<!--<%= link_to 'Back', videoconferencia_path %>-->
<% end %>

<% if cannot? :show, Videoconferencium %>
<div class= "contenedor">
    <div class="panel panel-default">
        <div class="panel-heading">Programación de actividades </div>
            <div class="panel-body"> 
                <center>
                  <div> No tienes acceso a esta página.</div>
                 <a class="btn btn-primary btn-large">
                 <%= button_to 'Regresar', calendario_actividadesInvestigacion_path, :method => :get %>
                 </a>
                 </center>
          
            </div>
        </div>      
</div>
<% end %>
<%= render 'welcome/piePagina', welcome: @welcome %>

app/views/videoconferencia/show.html.erb
<p id="notice"><%= notice %></p>
<div class="contenedor">
  <div class="panel panel-primary">
    <center>
      <div class="col-md-3" ></div>
      <div class="col-md-6">
       <ul class="list-group">

<li class="list-group-item list-group-item-info">
  <strong>Número de reservación:</strong>
  <%= @videoconferencium.id %>
</li>

<% if @videoconferencium.aprobacion == true %>
  <li class="list-group-item list-group-item-success">  Aprobación: Aprobada </li>
  <% else %>
  <li class="list-group-item list-group-item-danger"> Aprobación: Pendiente </li>
<% end %>

<li class="list-group-item">
  <strong>DATOS DEL SOLICITANTE</strong>
</li>

<li class="list-group-item">
  <strong>Nombre del solicitante:</strong>
  <%= @videoconferencium.nSolicitante %>
</li>

<li class="list-group-item">
  <strong>Título de la actividad:</strong>
  <%= @videoconferencium.tituloActividad %>
</li>

<li class="list-group-item">
  <strong>Coordinador:</strong>
  <%= @videoconferencium.coordinador %>
</li>

<li class="list-group-item">
  <strong>Fecha de la actividad:</strong>
  <%= @videoconferencium.fechaActividad %>
</li>

<li class="list-group-item">
  <strong>Hora de inicio:</strong>
  <%= @videoconferencium.horainicio %>
</li>

<li class="list-group-item">
  <strong>Hora de fin:</strong>
  <%= @videoconferencium.horafin %>
</li>

<li class="list-group-item">
  <strong>Fecha de solicitud:</strong>
  <%= @videoconferencium.fechaSolicitud %>
</li>

<li class="list-group-item">
  <strong>DATOS DEL ENLACE</strong>
</li>

<li class="list-group-item">
  <strong>Coordinador:</strong>
  <%= @videoconferencium.coordinadorEnlace %>
</li>

<li class="list-group-item">
  <strong>Responsable técnico:</strong>
  <%= @videoconferencium.responsableTecnico %>
</li>

<li class="list-group-item">
  <strong>Dirección IP:</strong>
  <%= @videoconferencium.numeroIP %>
</li>

<li class="list-group-item">
  <strong>Usuario:</strong>
  <%= @videoconferencium.usuarioTipoEnlace %>
</li>

<li class="list-group-item">
  <strong>Teléfono:</strong>
  <%= @videoconferencium.telefono %>
</li>

<li class="list-group-item">
  <strong>Correo electrónico:</strong>
  <%= @videoconferencium.correoElectronico %>
</li>

<li class="list-group-item">
  <strong>Recursos:</strong>
  <%= @videoconferencium.recursos %>
</li>
<li class="list-group-item">
  <strong>Hora de inicio:</strong>
  <%= @videoconferencium.horainicioEnlace %>
</li>
<li class="list-group-item">
  <strong>Hora de fin:</strong>
  <%= @videoconferencium.horafinEnlace %>
</li>

      </ul>

<h5><%= link_to 'Editar', edit_videoconferencium_path(@videoconferencium), :method =>:get %> |
<%= link_to 'Regresar', welcome_solicitud_path, :method => :get %> </h5>
</div>
</center>
</div>
</div>