config/routes.rb
Rails.application.routes.draw do

  resources :agendas
  #map.connect '/reservacions/solicitud', :controller => 'reservacions', :action => 'solicitud'
  
  resources :reservacions
  resources :welcome
  resources :calendario
  resources :reservacion
  resources :espacios
  resources :videoconferencia
  devise_for :users
  resources :users
  resources :reservacions, :member => {:solicitud => :get}
  
  
  root 'welcome#solicitud'

  get 'welcome/solicitud'
  post 'welcome/solicitud'

  get 'users/new'
  get 'users/edit'

  get 'welcome/administracion'
  post 'welcome/administracion'
   
  get 'calendario/espacios'
  post 'calendario/espacios'

  post 'calendario/salaVideoconferencia'

  post 'calendario/actividadesInvestigacion'
  post 'calendario/calendarioGeneral'

  get '/calendario/pdfs'
  #post '/calendario/pdfs'

  
  get 'espacios/auditorio4P'
  post 'espacios/auditorio4P'

  get 'espacios/sala15P'
  post 'espacios/sala15P'

  get   'espacios/sala25P'
  post 'espacios/sala25P'
 
  get   'espacios/auditorioRG'
  post 'espacios/auditorioRG'

  get 'espacios/sala6P'
  post 'espacios/sala6P'
 
  get 'espacios/salaPosg'
  post'espacios/salaPosg'

  get 'espacios/espacioAdic'
  post 'espacios/espacioAdic'


  get 'espacios/salaVideoconferencias'
  post 'espacios/salaVideoconferencias'

  get 'reservacions/new'
  get 'reservacions/show'
  get 'reservacions/formSala6', to: "reservacions#new"


  post '/reservacions/actividadesInvestigacion', to: 'reservacions#show'
  post '/reservacions/id', to: 'reservacions#show'
  post '/videoconferencia/id',  to: 'videoconferencia#show'

  get 'agendas/new'
  get 'agendas/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/espacio.rb
class Espacio < ApplicationRecord
	has_many :reservacions, dependent: :destroy


end

app/controllers/espacios_controller.rb
class EspaciosController < ApplicationController
protect_from_forgery

  before_action :set_espacio, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :handle_record_not_found
  # GET /espacios
  # GET /espacios.json
  def handle_record_not_found
    redirect_to calendario_actividadesInvestigacion_path
  end

  def index
    @espacios = Espacio.all
  end

  # GET /espacios/1
  # GET /espacios/1.json
  def show
   end

  # GET /espacios/new
  def new
    @espacio = Espacio.new
  end

  # GET /espacios/1/edit
  def edit
  end

  # POST /espacios
  # POST /espacios.json
  def create
    @espacio = Espacio.new(espacio_params)

    respond_to do |format|
      if @espacio.save
        format.html { redirect_to @espacio, notice: 'El espacio fue agregado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @espacio }
      else
        format.html { render :new }
        format.json { render json: @espacio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /espacios/1
  # PATCH/PUT /espacios/1.json
  def update
    respond_to do |format|
      if @espacio.update(espacio_params)
        format.html { redirect_to @espacio, notice: 'Los datos del espacio fueron actualizados satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @espacio }
      else
        format.html { render :edit }
        format.json { render json: @espacio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /espacios/1
  # DELETE /espacios/1.json
  def destroy
    @espacio.destroy
    respond_to do |format|
      format.html { redirect_to espacios_url, notice: 'Los datos del espacio fueron eliminados satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_espacio
      @espacio = Espacio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def espacio_params
      params.require(:espacio).permit(:nombre, :ubicacion, :aforo, :descripcion, :servicios_adicionales, :estatus)
    end
end

app/helpers/espacios_helper.rb
module EspaciosHelper
end

app/views/espacios/auditorio4P.html.erb
<html>

<head>
      <meta charset='utf-8' />
      <script src='https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script> 
      <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js'></script>
      <link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.5.1/fullcalendar.min.css" rel="stylesheet">
      <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.5.1/fullcalendar.min.js"> </script>
      <script src='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.6.1/locale/es.js'></script>
</head>
  <%= render 'welcome/encabezado', welcome: @welcome %>
<div class= "contenedor">
<div class="panel-group">
	<div class="col-md-3" >
	  <div class="panel panel-default">
      <div class="panel-heading">Programación de actividades </div>
      <% $espacioActual=1 %>
		    <div class="panel-body">
          <div class="btn-group-vertical" role="group" aria-label="...">
	  		      	Reservaciones
	
	  	      <button type="button" class="btn btn-link"></button>
            <%= javascript_include_tag "ventanaCatalogo" %>
      <div id="ventana_emergente"> 
         <h3> SERVICIOS TÉCNICOS </h3>
           <p> Videoproyector </p>
           <p> PC </p>
           <p> Traducción simultánea </p>
           <p> Vídeo </p>
           <p> Conexión por Skype </p>
           <p> Conexión Internet </p>
           <p> Videoconferencia </p>
           <p> Pizarrón </p>
           <p> Webcast </p>
           <p> Grabación de video </p>
           <p> Grabación de audio </p>
         <h3> OTROS SERVICIOS </h3>
           <p> En todas las sesiones se ofrece café. </p>
           <p> En sesiones de 3 horas o más se puede ofrecer galletas o fruta. </p>
           <p> <center><a class="btn btn-primary btn-xs" id="cerrar" href="javascript:void(0);"> Cerrar </a></center> </p>
      </div>
              <div> <a id="abrir" href="javascript:void(0);"> Cátalogo de servicios </a> </div>
          </div>
        </div>
    </div> </br></br></br>
      <div class="panel panel-default">
          <div class="panel-body">
            <div class="btn-group-vertical" role="group" aria-label="...">
              <center>
                <input type="text" readonly="true" style="background-color:red; color:white;" value=" SOLICITUD PENDIENTE">
                <input type="text" readonly="true" style="background-color:green; color:white;" value=" SOLICITUD APROBADA">
              </center>
            </div>
          </div>
      </div>
  </div>
</div>
<%= javascript_include_tag "cal_aud4P" %>

</head>

 <div class="panel-group">
  <div class="col-md-9" >
   <div class="panel panel-primary">
          <div class="panel-heading"> <center><h3>AUDITORIO 4° PISO</h3> </center></div>
        </div>
      <div id="calendarA4P"></div>
       <center>
           <div class="btn-group" role="group" aria-label="...">
            <center>
              <% if can? :manage, Reservacion %>
              <a class="btn btn-primary btn-large"><%= button_to 'Otro espacio', calendario_espacios_path, :method => :post %> </a>  
            <% else %>   
              <a class="btn btn-primary btn-large"><%= button_to 'Otro espacio', calendario_actividadesInvestigacion_path, :method => :get %> </a>
            <% end %> 
              <a class="btn btn-primary btn-large"> 
              <%= button_to 'Reservar', new_reservacion_path, :method => :get %> </a>
            </center>
           </div>
       </center>
  </div>       
 </div>
</div>
<%= render 'welcome/piePagina', welcome: @welcome %>
</html>

app/views/espacios/auditorioRG.html.erb
<html>
<%= render 'welcome/encabezado', welcome: @welcome %>
<head>
 
<meta charset='utf-8' />
 <script src='https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script> 
 <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js'></script>
 <link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.5.1/fullcalendar.min.css" rel="stylesheet">
 <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.5.1/fullcalendar.min.js"> </script>
 <script src='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.6.1/locale/es.js'></script>
 <script src= "//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.7.0/gcal.min.js"></script>

<div class= "contenedor">
<div class="panel-group">
  <div class="col-md-3" >
    <div class="panel panel-default">
       <div class="panel-heading"> Programación de actividades </div>
       <% $espacioActual=4 %>
		      <div class="panel-body">
             <div class="btn-group-vertical" role="group" aria-label="...">
	  		     Reservaciones
	      	   <button type="button" class="btn btn-link"></button>
           <%= javascript_include_tag "ventanaCatalogo" %>
        <div id="ventana_emergente"> 
         <h3> SERVICIOS TÉCNICOS </h3>
           <p> Videoproyector </p>
           <p> PC </p>
           <p> Traducción simultánea </p>
           <p> Vídeo </p>
           <p> Conexión por Skype </p>
           <p> Conexión Internet </p>
           <p> Videoconferencia </p>
           <p> Pizarrón </p>
           <p> Webcast </p>
           <p> Grabación de video </p>
           <p> Grabación de audio </p>
         <h3> OTROS SERVICIOS </h3>
           <p> En todas las sesiones se ofrece café. </p>
           <p> En sesiones de 3 horas o más se puede ofrecer galletas o fruta. </p>
           <p> <center> <a class="btn btn-primary btn-xs" id="cerrar" href="javascript:void(0);"> Cerrar </a> </center> </p>
        </div>
             <div>  <a id="abrir" href="javascript:void(0);"> Cátalogo de servicios </a> </div>
      
             </div>
          </div>
       </div> </br></br></br>
      <div class="panel panel-default">
          <div class="panel-body">
            <div class="btn-group-vertical" role="group" aria-label="...">
              <center>
                <input type="text" readonly="true" style="background-color:red; color:white;" value=" SOLICITUD PENDIENTE">
                <input type="text" readonly="true" style="background-color:green; color:white;" value=" SOLICITUD APROBADA">
              </center>
            </div>
          </div>
      </div>
   </div>
</div>

<%= javascript_include_tag "cal_audRG" %>
</head>

    <div class="panel-group">
	  <div class="col-md-9" >
      <div class="panel panel-primary">
        <div class="panel-heading"> <center><h3>AUDITORIO ROLANDO GARCÍA</h3> </center></div>
           </div>
          <div id="calendarARG"></div>
           <center>
           <div class="btn-group" role="group" aria-label="...">
            <center>
              <% if can? :manage, Reservacion %>   
               <a class="btn btn-primary btn-large"><%= button_to 'Otro espacio', calendario_espacios_path, :method => :post %> </a>
              <% else %>   
               <a class="btn btn-primary btn-large"><%= button_to 'Otro espacio', calendario_actividadesInvestigacion_path, :method => :get %> </a>
              <% end %> 
              <a class="btn btn-primary btn-large"> 
              <%= button_to 'Reservar', new_reservacion_path, :method => :get %> </a>
            </center>
           </div>
          </center>
      </div>
    </div>
</div>
<%= render 'welcome/piePagina', welcome: @welcome %>
</html>

app/views/espacios/edit.html.erb
<center>
<h1>Edición de espacios</h1>

<%= render 'form', espacio: @espacio %>

<%= link_to 'Mostrar', @espacio, :method =>:get %> |
<%= link_to 'Regresar', espacios_path, :method =>:get %>
</center>

app/views/espacios/espacioAdic.html.erb
<html>

<head>
      <meta charset='utf-8' />
      <script src='https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script> 
      <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js'></script>
      <link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.5.1/fullcalendar.min.css" rel="stylesheet">
      <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.5.1/fullcalendar.min.js"> </script>
      <script src='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.6.1/locale/es.js'></script>
</head>
  
<div class= "contenedor">
<div class="panel-group">
	<div class="col-md-3" >
	  <div class="panel panel-default">
      <div class="panel-heading">Programación de actividades </div>
		    <div class="panel-body">
          <div class="btn-group-vertical" role="group" aria-label="...">
	  		      	Reservaciones
	 
	  	      <button type="button" class="btn btn-link"></button>
            <%= javascript_include_tag "ventanaCatalogo" %>
      <div id="ventana_emergente"> 
         <h3> SERVICIOS TÉCNICOS </h3>
           <p> Videoproyector </p>
           <p> PC </p>
           <p> Traducción simultánea </p>
           <p> Vídeo </p>
           <p> Conexión por Skype </p>
           <p> Conexión Internet </p>
           <p> Videoconferencia </p>
           <p> Pizarrón </p>
           <p> Webcast </p>
           <p> Grabación de video </p>
           <p> Grabación de audio </p>
         <h3> OTROS SERVICIOS </h3>
           <p> En todas las sesiones se ofrece café. </p>
           <p> En sesiones de 3 horas o más se puede ofrecer galletas o fruta. </p>
           <p> <center><a class="btn btn-primary btn-xs" id="cerrar" href="javascript:void(0);"> Cerrar </a></center> </p>
      </div>
              <div> <a id="abrir" href="javascript:void(0);"> Cátalogo de servicios </a> </div>
          </div>
        </div>
    </div>
  </div>
</div>
<%= javascript_include_tag "cal_aud4P" %>

</head>

 <div class="panel-group">
  <div class="col-md-9" >
     <div class="panel panel-primary">
        <div class="panel-heading"> <center><h3>ESPACIO ADICIONAL</h3> </center></div>
      </div>
      <div id="calendar"></div>
        <center>
           <div class="btn-group" role="group" aria-label="...">
            <center>
              <a class="btn btn-primary btn-large">
              <%= button_to 'Otro espacio', calendario_espacios_path, :method => :get %> </a>
              <a class="btn btn-primary btn-large"> 
              <%= button_to 'Reservar', new_reservacion_path, :method => :get %> </a>
            </center>
           </div>
        </center>

  </div>
 </div>
</div>
</html>

app/views/espacios/index.html.erb
<p id="notice"><%= notice %></p>
<% if can? :manage, Espacio %>

<%= render 'welcome/administracion', welcome: @welcome %>

<div class="contenedor">
  <h1 align="center">Espacios</h1>
   <div align="right"><h4><%= link_to 'Nuevo espacio', new_espacio_path, :method => :get %></h4></div>
   <div class="panel panel-primary">
    <table class="table table-striped table-hover">

  <thead>
    <tr>
      <th>Nombre</th>
      <th>Ubicación</th>
      <th>Aforo</th>
      <th>Descripción</th>
      <th>Servicios adicionales</th>
      <th>Estatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @espacios.each do |espacio| %>
      <tr>
        <td><%= espacio.nombre %></td>
        <td><%= espacio.ubicacion %></td>
        <td><%= espacio.aforo %></td>
        <td><%= espacio.descripcion %></td>
        <td><%= espacio.servicios_adicionales %></td>
        <td><%= espacio.estatus %></td>
        <td><%= link_to 'Mostrar', espacio, :method => :get %></td>
        <td><%= link_to 'Editar', edit_espacio_path(espacio), :method => :get %></td>
        <td><%= link_to 'Eliminar', espacio, method: :delete, data: { confirm: '¿Desea continuar?' } %></td>
       
      </tr>
    <% end %> 
  </tbody>
</table>
<br>
</div>
<div align="right">
<%= button_to 'Sala de Videoconferencias', calendario_salaVideoconferencia_path, :method => :post %>
</div>

</div>
<% end %>

<% if cannot? :manage, Espacio %>
<div class= "contenedor">
    <div class="panel panel-default">
        <div class="panel-heading">Programación de actividades </div>
            <div class="panel-body"> 
                <center>
                  <div> No tienes acceso a esta página.</div>
                 <a class="btn btn-primary btn-large">
                 <%= button_to 'Regresar', calendario_actividadesInvestigacion_path, :method => :get %>
                 </a>
                 </center>
          
            </div>
        </div>      
</div>
<% end %>
<%= render 'welcome/piePagina', welcome: @welcome %>

app/views/espacios/sala15P.html.erb
<html>
  <head>
    <meta charset='utf-8' />
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script> 
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js'></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.5.1/fullcalendar.min.js"> </script>
    <script src='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.6.1/locale/es.js'></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.5.1/fullcalendar.min.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.css" rel="stylesheet" type="text/css">
    <link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.print.css " rel="stylesheet" type="text/css" media="print">
  </head>
<%= render 'welcome/encabezado', welcome: @welcome %>
  <div class= "contenedor">
    <div class="panel-group">
	    <div class="col-md-3" >
	      <div class="panel panel-default">
          <div class="panel-heading">Programación de actividades </div>
          <% $espacioActual=2 %>
		      <div class="panel-body">
            <div class="btn-group-vertical" role="group" aria-label="...">
		          Reservaciones
	  	        <button type="button" class="btn btn-link"></button>
              <%= javascript_include_tag "ventanaCatalogo" %>
              <div id="ventana_emergente"> 
                 <center>
                 <h3> EQUIPADA CON: </h3>
                   <p> Videoproyector </p>
                   <p> PC </p>
                   <p> Audio </p> 
                   <p> Conexión a Internet </p>   
                   <p> Pizarrón </p>
                   <p> <a class="btn btn-primary btn-xs" id="cerrar" href="javascript:void(0);"> Cerrar </a></p>
                 </center>
              </div>
              <div><a id="abrir" href="javascript:void(0);"> Cátalogo de servicios </a> </div>
            </div>
          </div>
        </div> </br></br></br>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="btn-group-vertical" role="group" aria-label="...">
              <center>
                <input type="text" readonly="true" style="background-color:red; color:white;" value=" SOLICITUD PENDIENTE">
                <input type="text" readonly="true" style="background-color:green; color:white;" value=" SOLICITUD APROBADA">
              </center>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "cal_sala15P" %>
    <div class="panel-group">
      <div class="col-md-9" >
        <div class="panel panel-primary">
          <div class="panel-heading"> <center><h3>SALA UNO 5° PISO </h3> </center></div>
        </div>
        <div id="calendar15P"></div>
        <center>
          <div class="btn-group" role="group" aria-label="...">
            <center>
              <% if can? :manage, Reservacion %>   
               <a class="btn btn-primary btn-large"><%= button_to 'Otro espacio', calendario_espacios_path, :method => :post %> </a>
              <% else %>   
               <a class="btn btn-primary btn-large"><%= button_to 'Otro espacio', calendario_actividadesInvestigacion_path, :method => :get %> </a>
              <% end %> 
              <a class="btn btn-primary btn-large"><%= button_to 'Reservar', new_reservacion_path, :method => :get %> </a>
              
          </div>
        </center>
      </div>
    </div>
  </div>
  <%= render 'welcome/piePagina', welcome: @welcome %>
</html>

app/views/espacios/sala25P.html.erb
<html>
  <head>
    <meta charset='utf-8' />
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script> 
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js'></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.5.1/fullcalendar.min.css" rel="stylesheet">
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.5.1/fullcalendar.min.js"> </script>
    <script src='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.6.1/locale/es.js'></script>
  </head>
<%= render 'welcome/encabezado', welcome: @welcome %>
  <div class= "contenedor">
    <div class="panel-group">
  	  <div class="col-md-3" >
  	    <div class="panel panel-default">
          <div class="panel-heading">Programación de actividades </div>
          <% $espacioActual=3 %>
  		    <div class="panel-body">
            <div class="btn-group-vertical" role="group" aria-label="...">
  		        Reservaciones
  	  	      <button type="button" class="btn btn-link"></button>
              <%= javascript_include_tag "ventanaCatalogo" %>
              <div id="ventana_emergente"> 
                <center>
                  <h3> EQUIPADA CON: </h3>
                  <p> Videoproyector </p>
                  <p> PC </p>
                  <p> Audio </p> 
                  <p> Conexión a Internet </p>   
                  <p> Pizarrón </p>
                  <p> <a class="btn btn-primary btn-xs" id="cerrar" href="javascript:void(0);"> Cerrar </a></p>
                </center>
              </div>
              <div> <a id="abrir" href="javascript:void(0);"> Cátalogo de servicios </a> </div>
            </div>
          </div>
        </div> </br></br></br>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="btn-group-vertical" role="group" aria-label="...">
              <center>
                <input type="text" readonly="true" style="background-color:red; color:white;" value=" SOLICITUD PENDIENTE">
                <input type="text" readonly="true" style="background-color:green; color:white;" value=" SOLICITUD APROBADA">
              </center>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "cal_sala25P" %>
    <div class="panel-group">
      <div class="col-md-9" >
        <div class="panel panel-primary">
          <div class="panel-heading"> <center><h3>SALA DOS 5° PISO </h3> </center></div>
        </div>
        <div id="calendar25P"></div>
        <center>
          <div class="btn-group" role="group" aria-label="...">
            <center>
              <% if can? :manage, Reservacion %>   
               <a class="btn btn-primary btn-large"><%= button_to 'Otro espacio', calendario_espacios_path, :method => :post %> </a>
              <% else %>   
               <a class="btn btn-primary btn-large"><%= button_to 'Otro espacio', calendario_actividadesInvestigacion_path, :method => :get %> </a>
              <% end %> 
              <a class="btn btn-primary btn-large"><%= button_to 'Reservar', new_reservacion_path, :method => :get %> </a>
            </center>
          </div>
        </center>
      </div>
    </div>
  </div>
  <%= render 'welcome/piePagina', welcome: @welcome %>
</html>

app/views/espacios/sala6P.html.erb
<html>
  <head>
    <meta charset='utf-8' />
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script> 
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js'></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.5.1/fullcalendar.min.js"> </script>
    <script src='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.6.1/locale/es.js'></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.5.1/fullcalendar.min.css" rel="stylesheet">
  </head>
<%= render 'welcome/encabezado', welcome: @welcome %>
  <div class= "contenedor">
    <div class="panel-group">
  	  <div class="col-md-3" >
  	    <div class="panel panel-default">
          <div class="panel-heading">Programación de actividades </div>
          <% $espacioActual= 5 %>
  		    <div class="panel-body">
            <div class="btn-group-vertical" role="group" aria-label="...">
  		        Reservaciones
  	          <button type="button" class="btn btn-link"></button>
              <%= javascript_include_tag "ventanaCatalogo" %>
              <div id="ventana_emergente"> 
                <center>
                  <h3> EQUIPADA CON: </h3>
                  <p> Videoproyector </p>
                  <p> PC </p>
                  <p> Audio </p> 
                  <p> Conexión a Internet </p>   
                  <p> Pizarrón </p>
                  <p> <a class="btn btn-primary btn-xs" id="cerrar" href="javascript:void(0);"> Cerrar </a></p>
                </center>
              </div>
              <div> <a id="abrir" href="javascript:void(0);"> Cátalogo de servicios </a> </div>
            </div>
          </div>
        </div> </br> </br> </br>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="btn-group-vertical" role="group" aria-label="...">
              <center>
                <input type="text" readonly="true" style="background-color:red; color:white;" value=" SOLICITUD PENDIENTE">
                <input type="text" readonly="true" style="background-color:green; color:white;" value=" SOLICITUD APROBADA">
              </center>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "cal_sala6P" %>
    <div class="panel-group">
	    <div class="col-md-9" >
        <div class="panel panel-primary">
          <div class="panel-heading"> <center><h3>SALA 6° PISO</h3> </center></div>
        </div>
        <div id="calendarS6P"></div>
        <center>
          <div class="btn-group" role="group" aria-label="...">
            <center>
              <% if can? :manage, Reservacion %>   
               <a class="btn btn-primary btn-large"><%= button_to 'Otro espacio', calendario_espacios_path, :method => :post %> </a>
              <% else %>   
               <a class="btn btn-primary btn-large"><%= button_to 'Otro espacio', calendario_actividadesInvestigacion_path, :method => :get %> </a>
              <% end %> 
              <a class="btn btn-primary btn-large"><%= button_to 'Reservar', new_reservacion_path, :method => :get %> </a>
            </center>
          </div>
        </center>
      </div>
    </div>
  </div>
  <%= render 'welcome/piePagina', welcome: @welcome %>
</html>

app/views/espacios/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "contenedor">
  <div class="container">
    <center>
    <div class="jumbotron4">
      
<p>
  <strong>ID:</strong>
  <%= @espacio.id %>
</p> 

<p>
  <strong>Nombre:</strong>
  <%= @espacio.nombre %>
</p>

<p>
  <strong>Ubicación:</strong>
  <%= @espacio.ubicacion %>
</p>

<p>
  <strong>Aforo:</strong>
  <%= @espacio.aforo %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @espacio.descripcion %>
</p>

<p>
  <strong>Servicios adicionales:</strong>
  <%= @espacio.servicios_adicionales %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @espacio.estatus %>
</p>

</div>

<%= link_to 'Editar', edit_espacio_path(@espacio), :method => :get %> |
<%= link_to 'Regresar', espacios_path, :method => :get %>
</center>
</div>
</div>