config/routes.rb
Rails.application.routes.draw do

  resources :agendas
  #map.connect '/reservacions/solicitud', :controller => 'reservacions', :action => 'solicitud'
  
  resources :reservacions
  resources :welcome
  resources :calendario
  resources :reservacion
  resources :espacios
  resources :videoconferencia
  devise_for :users
  resources :users
  resources :reservacions, :member => {:solicitud => :get}
  
  
  root 'welcome#solicitud'

  get 'welcome/solicitud'
  post 'welcome/solicitud'

  get 'users/new'
  get 'users/edit'

  get 'welcome/administracion'
  post 'welcome/administracion'
   
  get 'calendario/espacios'
  post 'calendario/espacios'

  post 'calendario/salaVideoconferencia'

  post 'calendario/actividadesInvestigacion'
  post 'calendario/calendarioGeneral'

  get '/calendario/pdfs'
  #post '/calendario/pdfs'

  
  get 'espacios/auditorio4P'
  post 'espacios/auditorio4P'

  get 'espacios/sala15P'
  post 'espacios/sala15P'

  get   'espacios/sala25P'
  post 'espacios/sala25P'
 
  get   'espacios/auditorioRG'
  post 'espacios/auditorioRG'

  get 'espacios/sala6P'
  post 'espacios/sala6P'
 
  get 'espacios/salaPosg'
  post'espacios/salaPosg'

  get 'espacios/espacioAdic'
  post 'espacios/espacioAdic'


  get 'espacios/salaVideoconferencias'
  post 'espacios/salaVideoconferencias'

  get 'reservacions/new'
  get 'reservacions/show'
  get 'reservacions/formSala6', to: "reservacions#new"


  post '/reservacions/actividadesInvestigacion', to: 'reservacions#show'
  post '/reservacions/id', to: 'reservacions#show'
  post '/videoconferencia/id',  to: 'videoconferencia#show'

  get 'agendas/new'
  get 'agendas/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calendario.rb
class Calendario < ApplicationRecord
end

app/controllers/calendario_controller.rb
class CalendarioController < ApplicationController
	#protect_from_forgery
	def show
		render '/calendario/actividadesInvestigacion'
	end

	def pdfs
		#render '/calendario/pdfs'
	end
end

app/helpers/calendario_helper.rb
module CalendarioHelper

end

app/views/calendario/actividadesInvestigacion.html.erb
<%= render 'welcome/encabezado', welcome: @welcome %>
<!DOCTYPE html>
<html>
 <head>
  <script type="text/javascript" src="https://code.jquery.com/jquery-1.8.3.js"></script>
 </head>
 
<% if can? :show, Reservacion %>
<body>
 <div class= "contenedor">
    <center><b><p id="notice"><%= notice %></p></br></center>
    <div class="panel-group">
	    <div class="col-md-2" >
	      <div class="panel panel-default">
          <div class="panel-heading">Reservaciones </div>
	        	<div class="panel-body">
             <div class="btn-group-vertical" role="group" aria-label="..."> 
                 
                  <h6> Consultar mi reservación. </h6>
                  <%= form_for :reservacion, url: reservacion_path(:id) do |f| %>
                    <div class="thumbnail">
                      <h7>Folio:</h7> 
                  <%= f.number_field :id, name:"id", min: "1", max: "99999", required:"" %>
                  
                  <center><%= f.submit "Consultar" %></center>
                     </div>
                  <% end %>      

             </div>
	          </div>
	      </div>
      </div>

      <div class="row">
        <div class="col-md-4" >
          <div class="panel1 panel-default">
            <ul class="thumbnails">
            <li class="span4">
            <div class="thumbnail">
              <%= image_tag "sala1_5p.jpg", :alt => "Sala uno 5° piso", :title => "Aforo: 16 personas" %>
            <center> 
              <a class="btn btn-primary btn-large">
                 <%= button_to 'Sala uno 5° piso', espacios_sala15P_path, :method => :post %>
             <form>
               <input name="id" type="hidden" value="2">
             </form> </a>
            </center> 
            </div>
            </li>

            <li class="span4">
            <div class="thumbnail">
              <%= image_tag "sala2_5p.jpg", :alt => "Sala dos 5° piso", :title => "Aforo: 16 personas" %>
            <center> 
              <a class="btn btn-primary btn-large">
                <%= button_to 'Sala dos 5° piso', espacios_sala25P_path, :method => :post %>
              <form>
                <input name="id" type="hidden" value="3">
              </form>  </a>
            </center> 
            </div> 
            </li>
            </ul>          
          </div>
        </div>
      
        <div class="col-md-1" >
          <div class="panel1 panel-default">
            <ul class="thumbnails">       
            </ul>          
          </div>
        </div>
     
        <div class="col-md-4" >
          <div class="panel1 panel-default">
            <ul class="thumbnails">
            <li class="span4">
            <div class="thumbnail">
              <%= image_tag "sala6p.jpg", :alt => "Sala del 6° piso", :title => "Aforo: 18 personas" %>
            <center> 
              <a class="btn btn-primary btn-large">
                <%= button_to 'Sala del 6° piso', espacios_sala6P_path, :method => :post %>
              <form>
                <input name="id" type="hidden" value="5">
              </form>  </a>
            </center> 
            </div> 
            </li>

            <li class="span4">
            <div class="thumbnail">
              <%= image_tag "sala_pos.jpg", :alt => "Sala de Posgrado", :title => "Aforo: 16 personas"%>
            <center> 
              <a class="btn btn-primary btn-large">
                <%= button_to 'Sala anexo CEIICH', espacios_salaPosg_path, :method => :post %>
              <form>
                <input name="id" type="hidden" value="6">
              </form> </a>
            </center> 
            </div>
            </li>
            </ul>          
          </div>
        </div>
        
      </div>
      </div>
    </div>
  </body>
<% end %>

<% if cannot? :show, Reservacion %>
<div class= "contenedor">
    <div class="panel panel-default">
        <div class="panel-heading">Programación de actividades </div>
            <div class="panel-body"> 
                <center>
                  <div> No tienes acceso a esta página.</div>
                 <a class="btn btn-primary btn-large">
                 <%= button_to 'Regresar', calendario_actividadesInvestigacion_path, :method => :get %>
                 </a>
                 </center>
          
            </div>
        </div>      
</div>
<% end %>
</html>
<%= render 'welcome/piePagina', welcome: @welcome %>

app/views/calendario/calendario.html.erb
<!DOCTYPE html>
<html>
 <head>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.8.3.js"></script>
    <script type="text/javascript">
       jQuery.fn.doModal = function(){
          var w = $(window).width();
          var h = $(window).height();
          var divW = $(this).width();
          var divH = $(this).height();
          $(this).css({
             'position': 'absolute',
             'left': (w/6)-(divW)+"px",
             'top': (h/3)-(divH)-"px",
             'z-index': '999'
          });
          $(this).fadeIn(500);
       }
       $(document).ready(function(){
          $("#abrir").click(function(){
          $("#ventana_emergente").doModal();
       });
       $("#cerrar").click(function(){
          $("#ventana_emergente").css('display', 'none');
       });
    });
 </script>
 </head>
<style type="text/css">
    #ventana_emergente {display: none; background-color: #fff; width: 300px; padding: 10px; border: solid 1px #000;}
 </style>
 <body>

<div class="panel-group">
	<div class="col-md-2" >
	 <div class="panel panel-default">
                <div class="panel-heading">Programación de actividades </div>
		<div class="panel-body">
                <div class="btn-group-vertical" role="group" aria-label="...">
	  		
		Reservaciones
	 
	  	<button type="button" class="btn btn-link"></button>
                <div>
        <a id="abrir" href="javascript:void(0);"> Cátalogo de servicios </a> </div>


<div id="ventana_emergente"> 
<h3> SERVICIOS TÉCNICOS </h3>
       <p> Videoproyector </p>
       <p> PC </p>
 <p> Traducción simultánea </p>
 <p> Vídeo </p>
 <p> Conexión por Skype </p>
 <p> Conexión Internet </p>
 <p> Videoconferencia </p>
 <p> Pizarrón </p>
 <p> Webcast </p>
<p> Grabación de video </p>
<p> Grabación de audio </p>
<h3> OTROS SERVICIOS </h3>
<p> En todas las sesiones se ofrece café. </p>
<p> En sesiones de 3 horas o más se puede ofrecer galletas o fruta. </p>
       <p> <a id="cerrar" href="javascript:void(0);"> Cerrar </a> </p>
    </div>

		</div>
	   </div>
	</div>
    </div>

 <div class="row">
         <div class="col-md-3" >
           <div class="panel panel-default">
<ul class="thumbnails">
  <li class="span4">
    <div class="thumbnail">
      <%= image_tag "aud4p.jpg", :alt => "Auditorio 4° piso" %>
<center> 
   <a class="btn btn-primary btn-large">
   <%= button_to 'Auditorio 4° piso', espacios_auditorio4P_path, :method => :post %>
    <form>
      <input name="id" type="hidden" value="1">
   </form>
    </a>
</center> 
    </div> 
</li>
<li class="span4">
<div class="thumbnail">
      <%= image_tag "sala1_5p.jpg", :alt => "Sala uno 5° piso" %>
     <center> 
   <a class="btn btn-primary btn-large">
    <style type="text/css">
input {color: black;}
    </style>
   <%= button_to 'Sala uno 5° piso', espacios_sala15P_path, :method => :post %>
    <form>
      <input name="id" type="hidden" value="2">
   </form>
    </a>
</center> 
    </div>
  </li>
</ul>          
</div>
</div>
 <div class="col-md-3" >
           <div class="panel panel-default">
<ul class="thumbnails">
  <li class="span4">
    <div class="thumbnail">
      <%= image_tag "sala2_5p.jpg", :alt => "Sala dos 5° piso" %>
<center> 
    <a class="btn btn-primary btn-large">
     <%= button_to 'Sala dos 5° piso', espacios_sala25P_path, :method => :post %>
     <form>
      <input name="id" type="hidden" value="3">
   </form>
    </a>
</center> 
  
    </div> 
</li>
<li class="span4">
<div class="thumbnail">
      <%= image_tag "aud5p.jpg", :alt => "Auditorio Rolando García" %>
     <center> 
   <a class="btn btn-primary btn-large">
   <%= button_to 'Auditorio "Rolando García"', espacios_auditorioRG_path, :method => :post %>
   <form>
      <input name="id" type="hidden" value="4">
   </form>
    </a>
</center> 
    </div>
  </li>
</ul>          
</div>
</div>
 <div class="col-md-3" >
           <div class="panel panel-default">
<ul class="thumbnails">
  <li class="span4">
    <div class="thumbnail">
      <%= image_tag "sala6p.jpg", :alt => "Sala del 6° piso" %>
     <center> 
   <a class="btn btn-primary btn-large">
   <%= button_to 'Sala del 6° piso', espacios_sala6P_path, :method => :post %>
   <form>
      <input name="id" type="hidden" value="5">
   </form>
    </a>
</center> 
    </div> 
</li>
<li class="span4">
<div class="thumbnail">
      <%= image_tag "sala_pos.jpg", :alt => "Sala de Posgrado" %>
      <center> 
   <a class="btn btn-primary btn-large">
   <%= button_to 'Sala de Posgrado', espacios_salaPosg_path, :method => :post %>
   <form>
      <input name="id" type="hidden" value="6">
   </form>
    </a>
</center> 
    </div>
  </li>
</ul>          
</div>
</div>
</div>
         
    </div>
</div>
 </body>
</html>

app/views/calendario/calendarioGeneral.html.erb
<%= render 'welcome/encabezado', welcome: @welcome %>
<html>
  <head>
    <meta charset='utf-8' />
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script> 
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js'></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.5.1/fullcalendar.min.js"> </script>
    <script src='//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.6.1/locale/es.js'></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.5.1/fullcalendar.min.css" rel="stylesheet">
  </head>

  <div class= "contenedor">
    <div class="panel-group">
      <center>
    <div class="col-md-4"></div>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading"> <center><h3> RESERVACIONES </h3> </center></div>
          <% $espacioActual=0 %>
          <div class="panel-body">
            <div class="btn-group-vertical" role="group" aria-label="...">
              <center>
                <input type="text" readonly="true" style="background-color:green; color:white;" value="SOLICITUDES CONFIRMADAS" size="25px"></br>
                <input type="text" readonly="true" style="background-color:red; color:white;" value="SOLICITUDES PENDIENTES" size="25px">
              </center>
            </div>
          </div>
        </div>
      </div>
    </center>
    </div>
    <%= javascript_include_tag "cal_global" %>
    <div class="panel-group">
      <div class="col-md-12" >
        <div id="calendarglobal"></div>
        <center>
          <div class="btn-group" role="group" aria-label="...">
            <% if can? :manage, Reservacion %>
            <center>
              <a class="btn btn-primary btn-large"><%= button_to 'Continuar', calendario_espacios_path, :method => :post %> </a>
            </center>
            <% else %>   
              <a class="btn btn-primary btn-large"><%= button_to 'Continuar', calendario_actividadesInvestigacion_path, :method => :get %> </a>
            <% end %> 

          </div>
        </center>
      </div>
    </div>
  </div>
</html>
<%= render 'welcome/piePagina', welcome: @welcome %>

app/views/calendario/espacios.html.erb
<%= render 'welcome/encabezado', welcome: @welcome %>
<!DOCTYPE html>
<html>
 <head>
  <script type="text/javascript" src="https://code.jquery.com/jquery-1.8.3.js"></script>
 </head>
<body>

   <div class= "contenedor">
    <div class="panel-group">
	    <div class="col-md-2" >
	      <div class="panel panel-default">
          <div class="panel-heading">Reservaciones </div>
	        	<div class="panel-body">
             <div class="btn-group-vertical" role="group" aria-label="...">
                
                <h6> Consultar mi reservación. </h6>
                  <%= form_for :reservacion, url: reservacion_path(:id) do |f| %>
                    <div class="thumbnail">
                      <h7>Folio:</h7> 
                  <%= f.number_field :id, name:"id", min: "1", max: "99999", required:"" %>
                  <center><%= f.submit "Consultar" %></center>
                     </div>
                  <% end %> 
    
             </div>
	          </div>
	      </div>
      </div>

      <div class="row">
        <div class="col-md-3" >
          <div class="panel1 panel-default">
            <ul class="thumbnails">
            <li class="span4">
            <div class="thumbnail">
            <%= image_tag "aud4p.jpg", :alt => "Auditorio 4° piso", :title => "Aforo: 70 personas" %>
            <center> 
              <a class="btn btn-primary btn-large">
                <%= button_to 'Auditorio 4° piso', espacios_auditorio4P_path, :method => :post %>
              <form>
                <input name="id" type="hidden" value="1">
              </form>  </a>
            </center> 
            </div> 
            </li>

            <li class="span4">
            <div class="thumbnail">
              <%= image_tag "sala1_5p.jpg", :alt => "Sala uno 5° piso", :title => "Aforo: 16 personas" %>
            <center> 
              <a class="btn btn-primary btn-large">
                 <%= button_to 'Sala uno 5° piso', espacios_sala15P_path, :method => :post %>
             <form>
               <input name="id" type="hidden" value="2">
             </form> </a>
            </center> 
            </div>
            </li>
            </ul>          
          </div>
        </div>
      
        <div class="col-md-3" >
          <div class="panel| panel-default">
            <ul class="thumbnails">
            <li class="span4">
            <div class="thumbnail">
              <%= image_tag "sala2_5p.jpg", :alt => "Sala dos 5° piso", :title => "Aforo: 16 personas" %>
            <center> 
              <a class="btn btn-primary btn-large">
                <%= button_to 'Sala dos 5° piso', espacios_sala25P_path, :method => :post %>
              <form>
                <input name="id" type="hidden" value="3">
              </form>  </a>
            </center> 
            </div> 
            </li>
          
            <li class="span4">
            <div class="thumbnail">
              <%= image_tag "aud5p.jpg", :alt => "Auditorio Rolando García", :title => "Aforo: 50 personas" %>
            <center> 
              <a class="btn btn-primary btn-large">
                <%= button_to 'Auditorio "Rolando García"', espacios_auditorioRG_path, :method => :post %>
              <form>
                <input name="id" type="hidden" value="4">
              </form>   </a>
            </center> 
            </div>
            </li>

           <!-- <li class="span4">
            <div class="thumbnail">
              <%= image_tag "salaVideoconferencias.jpg", :alt => "Otro espacio" %>
            <center> 
              <a class="btn btn-primary btn-large">
                <%= button_to 'Otro espacio', espacios_espacioAdic_path, :method => :post %>
              <form>
                <input name="id" type="hidden" value="7">
              </form>  </a>
            </center> 
            </div> 
            </li>-->
          
            </ul>          
          </div>
        </div>
     
        <div class="col-md-3" >
          <div class="panel| panel-default">
            <ul class="thumbnails">
            <li class="span4">
            <div class="thumbnail">
              <%= image_tag "sala6p.jpg", :alt => "Sala del 6° piso", :title => "Aforo: 18 personas" %>
            <center> 
              <a class="btn btn-primary btn-large">
                <%= button_to 'Sala del 6° piso', espacios_sala6P_path, :method => :post %>
              <form>
                <input name="id" type="hidden" value="5">
              </form>  </a>
            </center> 
            </div> 
            </li>

            <li class="span4">
            <div class="thumbnail">
              <%= image_tag "sala_pos.jpg", :alt => "Sala de Posgrado", :title => "Aforo: 16 personas"%>
            <center> 
              <a class="btn btn-primary btn-large">
                <%= button_to 'Sala anexo CEIICH', espacios_salaPosg_path, :method => :post %>
              <form>
                <input name="id" type="hidden" value="6">
              </form> </a>
            </center> 
            </div>
            </li>
            </ul>          
          </div>
        </div>
      </div>
      </div>
    </div>
  </body>
  <%= render 'welcome/piePagina', welcome: @welcome %>
</html>

app/views/calendario/pdfs.html.erb
<style type="button">
	input {color: black;}
</style>
<div class="container">
	<h4 align="center">CALENDARIOS (VERSIÓN IMPRIMIBLE)</h4></br></br></br>
		<div class="row">
			<div class="col-md-6">
				<div class="jumbotron5">
					<center>
						<a class="btn btn-primary btn-large">
							<%= button_to 'Generar pdf', reservacions_path(format: 'pdf'), :method => :get %>
						</a>
					</center>
				</div>
			</div>
		</div>
</div>
</br></br></br></br>

app/views/calendario/salaVideoconferencia.html.erb
<%= render 'welcome/encabezado', welcome: @welcome %>
<!DOCTYPE html>
<html>
 <head>
  <script type="text/javascript" src="https://code.jquery.com/jquery-1.8.3.js"></script>
 </head>

<% if can? :show, Videoconferencium %>
 <body>
   <div class= "contenedor">
    <div class="panel-group">
	    <div class="col-md-2" >
	      <div class="panel panel-default">
          <div class="panel-heading">Reservaciones </div>
	        	<div class="panel-body">
             <div class="btn-group-vertical" role="group" aria-label="...">
              
                  <h6> Consultar mi reservación. </h6>
                  <%= form_for :videoconferencia, url: videoconferencium_path(:id) do |f| %>
                    <div class="thumbnail">
                      <h7>Folio:</h7> 
                  <%= f.number_field :id, name:"id", min: "1", max: "99999", required:"" %>
                  <center><%= f.submit "Consultar" %></center>
                    </div>
                  <% end %>
                     
             </div>
	          </div>
	      </div>
      </div>

      <div class="row">
        <div class="col-md-2">
          <div class="panel1 panel-default">
            <ul class="thumbnails">
            </ul>          
          </div>
        </div>
      
        <div class="col-md-5" >
          <div class="panel1 panel-default">
            <ul class="thumbnails">
            <li class="span4">
            <div class="thumbnail">
              <%= image_tag "salaVideoconferencias.jpg", :alt => "Sala de Videoconferencias", :title => "Aforo: 18 personas" %>
            <center> 
              <a class="btn btn-primary btn-large">
                <%= button_to 'Sala de Videoconferencias', espacios_salaVideoconferencias_path, :method => :post %>
              <form>
                <input name="id" type="hidden" value="7">
              </form>  </a>
            </center> 
            </div> 
            </li>
            
            </ul>          
          </div>
        </div>
     
        <div class="col-md-3" >
          <div class="panel1 panel-default">
            <ul class="thumbnails">
            
            </ul>          
          </div>
        </div>
        
      </div>
      </div>
    </div>
  <body>
  <% end %>

<% if cannot? :show, Videoconferencium %>
<div class= "contenedor">
    <div class="panel panel-default">
        <div class="panel-heading">Programación de actividades </div>
            <div class="panel-body"> 
                <center>
                  <div> No tienes acceso a esta página.</div>
                 <a class="btn btn-primary btn-large">
                 <%= button_to 'Regresar', calendario_actividadesInvestigacion_path, :method => :get %>
                 </a>
                 </center>
            </div>
    </div>      
</div>
<% end %>
</html>
<%= render 'welcome/piePagina', welcome: @welcome %>